version: "3.9"

services:
  mysql_db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=searchEngine
    #volumes:
     # - mysqldb-searchEngine-data:/var/lib/mysql
    
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/searchEngine
    depends_on:
      - mysql_db
    links:
      - mysql_db
    restart: on-failure:10

# volumes:
#   mysqldb-searchEngine-data:
      